#ifndef VIEWLETVIEW_HPP
#define VIEWLETVIEW_HPP

#include "config.h"

extern "C"
{
#include "qof.h"
#include "engine/Account.h"
#include "engine/Transaction.h"
#include "engine/Split.h"
}

#include "gnc/mainwindow.hpp"
#include "gnc/fpo/ViewletModel.hpp"
#include "gnc/AccountItemModel.hpp"
#include "gnc/SplitListModel.hpp"

#include <QtCore>
#include <QAbstractItemModel>
#include <QtGui>
#include <QWidget>

namespace gnc
{
class ViewletModel;

class ViewletView : public QWidget
{
    Q_OBJECT
public:
    explicit ViewletView(QWidget * parent = 0, QHBoxLayout * FPOLayout = NULL);
    void loadAccountsTreeComboBox(AccountListModel * const m_accountsListModel);

    /* Call the appropriate method to set the viewlet of that type */
    void defaultVSet(QWidget * parent, QHBoxLayout * FPOLayout);
    void leftVSet(QWidget * parent, QHBoxLayout * FPOLayout);
    void rightVSet(QWidget * parent, QHBoxLayout * FPOLayout);

signals:

public slots:

private:
    ViewletModel *viewletModel;
    AccountListModel *accountsList;

    enum
    {
        TXN_DESC = "descWidget",
        SPLIT_ACCT = "accountWidget"
    } id;

    QString txnDescription;
    QString splitAccount;

    QVBoxLayout *defaultVLayout;
    QVBoxLayout *leftVLayout;
    QVBoxLayout *rightVLayout;

    /* A simple list to store widgets generated by any of the three
       viewlet types */
    QList<QWidget *> viewletWidgetsList;

    /** @bugid_1 */
    QComboBox * comboAccountsList;    

    /** @todo */
    SplitList * pSplitList;
    ::Account * selectedAccount;
    int selectedAccountIndex;

    /* Widget generators */
    void setLabel(QString data, QString objectName, QVBoxLayout *layout);

    /* Viewlet generator methods */
    void defaultVDraw();
    void defaultVRemoveWidgets();
    void leftVDraw();
    void leftVRemoveWidgets();
    void rightVDraw();
    void rightVRemoveWidgets();

private slots:
    void defaultVUpdate();
    //void leftVUpdate();
    //void rightVUpdate();
};

} // END namespace gnc

#endif // VIEWLETVIEW_HPP
